### PR TITLE
fix client setup script for pypi

### PR DESCRIPTION
**Pull request by tianweidut**
## Description
build and upload pypi.org : https://pypi.org/project/starwhale/
create your venv , and then run `pip install starwhale==0.1.0.dev0`

image
image
image

## Modules
- [x] Others

## Checklist
- [ ] run code format and lint check
- [ ] add unit test
- [ ] add necessary doc

### CODE REVIEW

**Comment by goldenxinxing** [comment]
Is it possible to merge it, see that there is still “wip” on the title @tianweidut

**Review by goldenxinxing — APPROVED** [review]
lgtm

**Comment by tianweidut** [comment]
> Is it possible to merge it, see that there is still “wip” on the title @tianweidut

@goldenxinxing  still work in progress

**Comment by tianweidut** [comment]
@goldenxinxing  ready to merge, thanks

**Review by anda-ren — APPROVED** [review]
LGTM

**Review by goldenxinxing — APPROVED** [review]
lgtm

**Pull request merged**
