### PR TITLE
chore(doc): add example doc for ucf101

### PR DESCRIPTION
**Pull request by goldenxinxing**
## Modules
- [ ] UI
- [ ] Controller
- [ ] Agent
- [ ] Client
- [ ] Python-SDK
- [x] Others

## Checklist
- [ ] run code format and lint check
- [ ] add unit test
- [x] add necessary doc

### CODE REVIEW

**Comment by jialeicui** [comment]
- Link this file to ucf101/README-zh.md?
- Could you add the ufc101 link to the sidebar when the en version is ready?

**Comment by tianweidut** [comment]
Others LGTM

**Comment by tianweidut** [comment]
@goldenxinxing  add an English doc?

**Comment by goldenxinxing** [comment]
> * Link this file to ucf101/README-zh.md?
> * Could you add the ufc101 link to the sidebar when the en version is ready?

done

**Comment by goldenxinxing** [comment]
> @goldenxinxing add an English doc?

done

**Review by jialeicui — APPROVED** [review]

**Pull request merged**
