### PR TITLE
runtime related change

### PR DESCRIPTION
**Pull request by anda-ren**
## Description
- replace base image to runtime in job create api **request** @waynelwz @tianweidut 
- replace base image to runtime in task report api **response** @goldenxinxing  
- replace base image to runtime in job view api **response** @waynelwz @tianweidut 

### Job create api

**Request For List Job**

```
curl -X 'GET' \
  'http://localhost:8082/api/v1/project/1/job?pageNum=1&pageSize=10' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHN0YXJ3aGFsZSIsImlzcyI6InN0YXJXaGFsZSIsImlhdCI6MTY1NDQ5NzkzMSwiZXhwIjoxNjU3MDg5OTMxfQ.UL1BVp3Z_l_xqGQKk-Q3mFZu1i8yHrf6eD-XC3gdOBOHlzbSgLViYzdvoFj1CWjNJzL5EN90OctOFRuhL8_now'
```

**Response For List Job**

```
{
  "code": "success",
  "message": "Success",
  "data": {
    "total": 1,
    "list": [
      {
        "id": "1",
        "uuid": "1c17295711e34d5b8cc12c9b62d3efc7",
        "modelName": "cifar_net",
        "modelVersion": "hfqtimrxgy4gcztfgq4gmzten42gc6a",
        "datasets": null,
        "runtime": {
          "id": "1",
          "name": "test_name",
          "createdTime": 1654469377000,
          "owner": {
            "id": "1",
            "name": "starwhale",
            "createdTime": 1654458401000,
            "role": {
              "id": "1",
              "roleName": "admin",
              "roleNameEn": "admin"
            },
            "isEnabled": true
          },
          "version": {
            "id": "1",
            "name": "testversion",
            "tag": null,
            "meta": "asd",
            "createdTime": 1654469404000,
            "owner": {
              "id": "1",
              "name": "starwhale",
              "createdTime": 1654458401000,
              "role": {
                "id": "1",
                "roleName": "admin",
                "roleNameEn": "admin"
              },
              "isEnabled": true
            }
          }
        },
        "device": "CPU",
        "deviceAmount": 1,
        "owner": {
          "id": "1",
          "name": "starwhale",
          "createdTime": 1654458401000,
          "role": {
            "id": "1",
            "roleName": "admin",
            "roleNameEn": "admin"
          },
          "isEnabled": true
        },
        "createdTime": 1654498233000,
        "stopTime": 1654498464000,
        "jobStatus": "SUCCESS",
        "comment": null,
        "duration": 231000
      }
    ],
    "pageNum": 1,
    "pageSize": 10,
    "size": 1,
    "startRow": 0,
    "endRow": 10,
    "pages": 1,
    "prePage": 0,
    "nextPage": 0,
    "isFirstPage": true,
    "isLastPage": true,
    "hasPreviousPage": false,
    "hasNextPage": false,
    "navigatePages": 8,
    "navigatepageNums": [
      1
    ],
    "navigateFirstPage": 1,
    "navigateLastPage": 1
  }
}
```
**Request For Job Info**
```
curl -X 'GET' \
  'http://localhost:8082/api/v1/project/1/job/1' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHN0YXJ3aGFsZSIsImlzcyI6InN0YXJXaGFsZSIsImlhdCI6MTY1NDQ5NzkzMSwiZXhwIjoxNjU3MDg5OTMxfQ.UL1BVp3Z_l_xqGQKk-Q3mFZu1i8yHrf6eD-XC3gdOBOHlzbSgLViYzdvoFj1CWjNJzL5EN90OctOFRuhL8_now'
```
**Response For Job Info**
```
{
  "code": "success",
  "message": "Success",
  "data": {
    "id": "1",
    "uuid": "1c17295711e34d5b8cc12c9b62d3efc7",
    "modelName": "cifar_net",
    "modelVersion": "hfqtimrxgy4gcztfgq4gmzten42gc6a",
    "datasets": [
      "g4ytezbqgfrtmodche3wcnrupfwta5a"
    ],
    "runtime": {
      "id": "1",
      "name": "test_name",
      "createdTime": 1654469377000,
      "owner": {
        "id": "1",
        "name": "starwhale",
        "createdTime": 1654458401000,
        "role": {
          "id": "1",
          "roleName": "admin",
          "roleNameEn": "admin"
        },
        "isEnabled": true
      },
      "version": {
        "id": "1",
        "name": "testversion",
        "tag": null,
        "meta": "asd",
        "createdTime": 1654469404000,
        "owner": {
          "id": "1",
          "name": "starwhale",
          "createdTime": 1654458401000,
          "role": {
            "id": "1",
            "roleName": "admin",
            "roleNameEn": "admin"
          },
          "isEnabled": true
        }
      }
    },
    "device": "CPU",
    "deviceAmount": 1,
    "owner": {
      "id": "1",
      "name": "starwhale",
      "createdTime": 1654458401000,
      "role": {
        "id": "1",
        "roleName": "admin",
        "roleNameEn": "admin"
      },
      "isEnabled": true
    },
    "createdTime": 1654498233000,
    "stopTime": 1654498464000,
    "jobStatus": "SUCCESS",
    "comment": null,
    "duration": 231000
  }
}
```

### Job create api
```
curl -X 'POST' \
  'http://localhost:8082/api/v1/project/1/job' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHN0YXJ3aGFsZSIsImlzcyI6InN0YXJXaGFsZSIsImlhdCI6MTY1NDQ5NzkzMSwiZXhwIjoxNjU3MDg5OTMxfQ.UL1BVp3Z_l_xqGQKk-Q3mFZu1i8yHrf6eD-XC3gdOBOHlzbSgLViYzdvoFj1CWjNJzL5EN90OctOFRuhL8_now' \
  -H 'Content-Type: application/json' \
  -d '{
  "modelVersionId": "1",
  "datasetVersionIds": "1",
  "runtimeVersionId": "1",
  "deviceId": "1",
  "deviceAmount": 1
}'
```

## Modules
- [ ] UI
- [x] Controller
- [ ] Agent
- [ ] Client
- [ ] Python-SDK
- [ ] Others

## Checklist
- [ ] run code format and lint check
- [ ] add unit test
- [x] add necessary doc

### CODE REVIEW

**Review by goldenxinxing — APPROVED** [review]
lgtm

**Comment by tianweidut** [comment]
LGTM

**Review by dreamlandliu — APPROVED** [review]
LGTM

**Comment by tianweidut** [comment]
cli related pr: https://github.com/star-whale/starwhale/pull/504

**Pull request merged**
