### PR TITLE
chore: disable blob cache by default

### PR DESCRIPTION
**Pull request by jialeicui**
## Modules
- [ ] UI
- [ ] Controller
- [ ] Agent
- [x] Client
- [ ] Python-SDK
- [ ] Others

## Checklist
- [x] run code format and lint check
- [x] add unit test
- [ ] add necessary doc

### CODE REVIEW

**Comment by jialeicui** [comment]
wait for https://github.com/lundberg/respx/pull/278

**Comment by jialeicui** [comment]
related to https://github.com/star-whale/starwhale/issues/3143

**Comment by lundberg** [comment]
> wait for [lundberg/respx#278](https://github.com/lundberg/respx/pull/278)

RESPX version `0.22.0` released

**Comment by jialeicui** [comment]
> > wait for [lundberg/respx#278](https://github.com/lundberg/respx/pull/278)
> 
> RESPX version `0.22.0` released

Thank you @lundberg  for your reminder and @ndhansen for the PR. Your contributions are greatly appreciated and have been very helpful to our project.

**Review by tianweidut — APPROVED** [review]
LGTM

**Pull request merged**
