### PR TITLE
bug(client): fix local wheel package unexpected freezing issue

### PR DESCRIPTION
**Pull request by tianweidut**
## Description
image

By default, the local wheel packages should not be locked into the requirements-sw-lock.txt file which will lead to runtime restore failure.

## Modules
- [x] Client

## Checklist
- [x] run code format and lint check
- [ ] add unit test
- [ ] add necessary doc

### CODE REVIEW

**Comment by jialeicui** [comment]
Will the wheel pkg work as expected if it is packaged?

**Comment by tianweidut** [comment]
> Will the wheel pkg work as expected if it is packaged?

yes, the phase of runtime restoring will install whl by the runtime.yaml.  @jialeicui

**Review by jialeicui — APPROVED** [review]
LGTM

**Review by goldenxinxing — APPROVED** [review]
LGTM

**Pull request merged**
