### PR TITLE
feat(sdk): build datasets and models using tmp dir

### PR DESCRIPTION
**Pull request by jialeicui**
## Modules
- [ ] UI
- [ ] Controller
- [ ] Agent
- [x] Client
- [x] Python-SDK
- [ ] Others

## Checklist
- [x] run code format and lint check
- [x] add unit test
- [ ] add necessary doc

### CODE REVIEW

**Comment by jialeicui** [comment]
relates to #691

**Comment by tianweidut** [comment]
@jialeicui  add [gc](https://github.com/star-whale/starwhale/blob/main/client/starwhale/mngt/__init__.py#L19) for tmpdir ?

**Comment by jialeicui** [comment]
> @jialeicui add [gc](https://github.com/star-whale/starwhale/blob/main/client/starwhale/mngt/__init__.py#L19) for tmpdir ?

done

**Review by tianweidut — APPROVED** [review]
LGTM

**Pull request merged**
