### PR TITLE
Add REST Api - list swmp/swds by version ids

### PR DESCRIPTION
**Pull request by dreamlandliu**
* list models by version ids
* list datasets by version ids

## Modules
- [ ] UI
- [x] Controller
- [ ] Agent
- [ ] Client
- [ ] Python-SDK
- [ ] Others

## Checklist
- [ ] run code format and lint check
- [ ] add unit test
- [ ] add necessary doc

### CODE REVIEW

**Review by tianweidut — DISMISSED** [review]
LGTM

**Comment by tianweidut** [comment]
@dreamlandliu  need resolve some conflicts

**Comment by dreamlandliu** [comment]
> @dreamlandliu need resolve some conflicts

done

**Review by anda-ren — APPROVED** [review]
lgtm

**Pull request merged**
