### PR TITLE
lint:  typescipt / eslint lint passed

### PR DESCRIPTION
**Pull request by waynelwz**
## Modules
- [x] UI

## Checklist
- [x] run code format and lint check
- [ ] add unit test
- [ ] add necessary doc

### CODE REVIEW

**Comment by tianweidut** [comment]
@waynelwz  add github action for js/ts lint ?

**Comment by waynelwz** [comment]
> @waynelwz add github action for js/ts lint ?
sure, later

**Comment by waynelwz** [comment]
ci passed with cache.

checkout：

image

https://github.com/waynelwz/starwhale/runs/6333825698?check_suite_focus=true

**Review by tianweidut — APPROVED** [review]
LGTM

**Pull request merged**
